---
- hosts: ws
  become: yes
  tasks:
    - name: Install Packages
      package:
        state: present
        name:
        - lsof
        - wget
        - docker.io
        - unzip
        - curl
    
    - name: Create a directory
      file:
        state: directory
        path: /opt/qa/spg
        mode: '0755'
        

    - name: Create log file
      file:
        state: touch
        path: /opt/qa/spg/spg.log
    
    - name: Start and enable daemon
      systemd:
        name: docker.io
        state: started
        enabled: yes
        